### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Refra879** [ManneN1/OmniBar-MoP#1]
My wow do not recognize the addon and it does not appear to check it

**Comment by ManneN1** [comment]
You probably didnt rename the folder correctly as outlined at the very top of the README file.

But, since you closed the ticket you probably realized it already.

**Comment by Refra879** [comment]
Ye, i didnt rename it, ty. Do you know any Sarena like Retail?

**Comment by ManneN1** [comment]
No, I dont use sArena.
